---
abstract: 'a perl module for creating identifiers with a per digit base'
author: []
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-BaseMulti
provides:
  Math::BaseMulti:
    file: lib/Math/BaseMulti.pm
requires:
  Moose: 1.00
  perl: v5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
